name: CI-CD_-FastAPI_pull_request

on:
  pull_request:
    branches:
      - master

jobs:
  welcome_script:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome part
        run: echo "Hello, guys"
      - name: Get info
        run: |
          echo "Hello from workflow"
          whoami
          sleep 5
          pwd
